default:
  image: python:3.8

variables:
  DATA_PATH: $CI_PROJECT_DIR/tests/data/

test:
  script:
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - python3 -m pip install --user -r requirements.txt
  - python3 -m nltk.downloader stopwords
  - python3 -m nltk.downloader punkt
  - python3 -m nltk.downloader averaged_perceptron_tagger
  - python3 -m nltk.downloader wordnet
  - python3 -m nltk.downloader vader_lexicon
  - python3 -m nltk.downloader wordnet_ic  
  - python3 -m nltk.downloader omw-1.4  
  - python3 setup.py test
