variables:
  DATA_PATH: $CI_PROJECT_DIR/tests/data/

test:
  script:
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader punkt
  - python -m nltk.downloader averaged_perceptron_tagger
  - python -m nltk.downloader wordnet
  - python setup.py test
