site_name: GSItk Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Publications: publications.md
  - User guide:
      - Datasets: datasets.md
      - Preprocessing: preprocessing.md
      - Feature extraction: features.md
      - Evaluation : evaluation.md
      - Classifiers: classifiers.md
