site_name: GSItk Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Publications: publications.md
  - Tutorial: Tutorial.ipynb
  - User guide:
      - Datasets: datasets.md
      - Preprocessing: preprocessing.md
      - Feature extraction: features.md
      - Classifiers: classifiers.md
      - Evaluation : evaluation.md

plugins:
  - mknotebooks
