site_name: GSItk Documentation - by Oscar
theme: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - User guide:
      - Datasets: datasets.md
      - Preprocessing: preprocessing.md
      - Feature extraction: features.md
      - Evaluation : evaluation.md
